# Generated by Django 3.2.14 on 2022-07-26 09:18

from django.db import migrations, models
import resolwe.observers.models


class Migration(migrations.Migration):

    dependencies = [
        ('observers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='observable',
            field=models.CharField(default=resolwe.observers.models.get_random_hash, max_length=32, unique=True),
        ),
    ]
