name: Resolwe CI

on:
  push:
    branches:
      - master
      - arc-runners # TODO: remove
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

  pull_request:
  schedule:
    - cron: "30 2 * * *"

jobs:
  test:
    runs-on: arc-runner
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.10"
            toxenv: "py310"
            codecov: false
          - python: "3.11"
            toxenv: "py311"
            codecov: true
          - python: "3.11"
            toxenv: "linters"
            codecov: false
          - python: "3.11"
            toxenv: "packaging"
            codecov: false
          - python: "3.11"
            toxenv: "migrations"
            codecov: false
    container:
      image: 342286153875.dkr.ecr.us-east-1.amazonaws.com/genialis/ci/arc-runner:latest
      env:
        # DOCKER_HOST: unix:///run/docker/docker.sock
        RESOLWE_REDIS_PORT: 6379
        RESOLWE_POSTGRESQL_HOST: localhost
        RESOLWE_POSTGRESQL_NAME: resolwe
        RESOLWE_POSTGRESQL_USER: resolwe
        RESOLWE_POSTGRESQL_PASS: resolwe
        RESOLWE_POSTGRESQL_PORT: 5432
      # volumes:
      #   - /run/docker:/var/run/docker
      credentials:
        username: AWS
        password: ${{ secrets.AWS_ECR_PASSWORD }}

    services:
      postgres: 
        image: postgres:14-alpine
        env:
          POSTGRES_USER: resolwe
          POSTGRES_DB: resolwe
          POSTGRES_PASSWORD: resolwe
        ports: 
          - 5432/tcp

      redis:
        image: redis:alpine
        ports: 
          - 6379/tcp

    steps:
      - uses: actions/checkout@v4

      - name: Build communication container
        working-directory: ./resolwe/flow/docker_images
        run: docker build -f Dockerfile.communication -t resolwe/com:testing ../../

      - name: Run Tests
        run: >
          RESOLWE_COMMUNICATOR_IMAGE=resolwe/com:testing
          python3.12 -m tox -e ${{ matrix.toxenv }}
          --skip-missing-interpreters false
          --recreate

      - name: Upload coverage to Codecov
        if: matrix.codecov
        uses: codecov/codecov-action@v4
        with:
          file: .coverage

  build:
    runs-on: ubuntu-22.04
    needs: test
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v4

      - name: Install build
        run: python -m pip install --user build

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}
